import psycopg2
import os
from werkzeug.security import generate_password_hash
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

DATABASE_URL = os.environ.get("DATABASE_URL")
ADMIN_USERNAME = os.environ.get("ADMIN_USERNAME")
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD")

conn = psycopg2.connect(DATABASE_URL)
cur = conn.cursor()

# Create tables
cur.execute("""
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        username TEXT NOT NULL UNIQUE,
        password TEXT NOT NULL
    )
""")

cur.execute("""
    CREATE TABLE IF NOT EXISTS projects (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL UNIQUE,
        description TEXT,
        languages TEXT,
        img TEXT,
        video TEXT,
        git_url TEXT,
        live_url TEXT,
        "order" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE
    )
""")

cur.execute("""
    CREATE TABLE IF NOT EXISTS contact (
        id SERIAL PRIMARY KEY,
        fname TEXT NOT NULL,
        lname TEXT NOT NULL,
        email TEXT NOT NULL,
        message TEXT NOT NULL
    )
""")

# Insert default user (only if not exists)
default_username = ADMIN_USERNAME
default_password = generate_password_hash(ADMIN_PASSWORD) 

cur.execute("""
    INSERT INTO users (username, password)
    VALUES (%s, %s)
    ON CONFLICT (username) DO NOTHING
""", (default_username, default_password))

# Insert projects
projects = [
    ("Online Movies Web", "A website that simulates a store where the users can buy movies. Also there's a dashboard where the admin can control the database.", "HTML, CSS, Bootstrap, PHP, MySQL", "https://res.cloudinary.com/djxujz9qp/image/upload/v1769110829/portfolio/images/qp6hkaj6vcwgagr0msmm.png", "https://www.youtube.com/watch?v=7FtVBAl0g8w", "https://github.com/JanNievesCedeno/OnlineMoviesWeb", "https://onlinemoviesweb.wuaze.com/index.php"),
    ("Online Movies Android App", "Mobile App for Android that simulates a store where the user can buy movies. Also there's a dashboard where the admin can control the database.", "Android Studio, Java, Sqlite", "https://res.cloudinary.com/djxujz9qp/image/upload/v1769111270/portfolio/images/xqvrju5fnqdlaipxsw1x.png", "https://www.youtube.com/watch?v=RREv3vljJYQ", "https://github.com/JanNievesCedeno/OnlineMoviesAndroid", None),
    ("PortfolioApp", "Website to show my skills", "Flask, Python, Html, Css, Bootstrap, PostgreSQL", "https://res.cloudinary.com/djxujz9qp/image/upload/v1769111903/portfolio/images/ghqnf24owgkybfjsxwzw.png", "https://www.youtube.com/watch?v=pGhn7y1IWLY", "https://github.com/JanNievesCedeno/PortfolioApp", None)
]

for project in projects:
    cur.execute("""
        INSERT INTO projects (name, description, languages, img, video, git_url, live_url)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT (name) DO NOTHING
    """, project)


conn.commit()
cur.close()
conn.close()

print("Database initialized successfully!")